# RVM - autogenerated during install
[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*





########## ALIAS COMMANDS ##########
# 1) StarT postgres manually instead of using brew service
alias psqlgo='pg_ctl -D /usr/local/var/postgres start'

# 2) Reboot pow and rails app
alias powrestart='touch ~/.pow/restart.txt && touch tmp/restart.txt'

# 3) Reload bash instead of kill terminal
alias reloadbash='source ~/.bash_profile'

########## END ALIAS ##########





# Git branch in prompt
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\u@\h \W\[\033[35m\]\$(parse_git_branch)\[\033[00m\] $ "
